spring.application.name=projecte3

server.port=2006

spring.data.mongodb.uri=mongodb://localhost:27017/projecte3_db
spring.data.mongodb.database=projecte3_db

logging.level.org.springframework.data.mongodb=DEBUG